# Generated by Django 5.2.10 on 2026-09-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliovideo',
            old_name='cloudflare_video_uid',
            new_name='imagekit_file_id',
        ),
    ]
