# Generated by Django 5.2.17 on 2026-09-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cloudflare_video_uid_portfoliovideo_imagekit_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('portrait', 'Portrait'), ('travel', 'Travel'), ('food', 'Food & Lifestyle'), ('fitness', 'Fitness'), ('product', 'Product'), ('wedding', 'Wedding'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=30)),
                ('image_url', models.TextField(blank=True, help_text='Base64 encoded image or remote URL', null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_public', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_photos', to='core.shooterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PortfolioVideo',
        ),
    ]
