# Generated by Django 5.2.17 on 2026-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfoliophoto_delete_portfoliovideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name shown in dropdown (e.g. Reel Shooter)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe key used in code (e.g. reel_shooter)', max_length=100, unique=True)),
                ('icon_emoji', models.CharField(blank=True, default='🎥', help_text='Emoji icon shown next to category name', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Short description of this creator type')),
                ('is_active', models.BooleanField(default=True, help_text='Only active categories appear in the frontend dropdown')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first in dropdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Creator Category',
                'verbose_name_plural': 'Creator Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
