# Generated by Django 5.2.17 on 2026-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creatorcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooterprofile',
            name='category',
            field=models.CharField(blank=True, default='reel_shooter', help_text='Slug of admin-managed CreatorCategory (e.g. reel_shooter, photographer)', max_length=100),
        ),
    ]
