# Generated by Django 5.2.10 on 2026-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shooterprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooterprofile',
            name='packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shooterprofile',
            name='portfolio',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
