# Generated by Django 5.2.17 on 2026-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shooterprofile_packages_shooterprofile_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Create Amazing Reels', help_text="Main heading on banner, e.g. 'Create Amazing Reels'", max_length=200)),
                ('subtitle', models.TextField(blank=True, default='Find the best reel shooters, photographers & creators near you.', help_text='Supporting subtext or description')),
                ('badge_text', models.CharField(blank=True, default='Your Creative Partner', help_text="Pill tag shown above title, e.g. 'Your Creative Partner'", max_length=80)),
                ('tagline_text', models.CharField(blank=True, default='Your Story Our Creators', help_text="Accent script text on the right side, e.g. 'Your Story Our Creators'", max_length=120)),
                ('button_text', models.CharField(default='Book Now', help_text='Text shown on CTA button', max_length=60)),
                ('button_action', models.CharField(default='search', help_text="Action screen or URL, e.g. 'search', 'reel_shooter'", max_length=100)),
                ('category_slug', models.CharField(blank=True, default='reel_shooter', help_text="Category to filter when clicked (e.g. 'reel_shooter', 'all')", max_length=80)),
                ('image', models.ImageField(blank=True, help_text='Upload banner image directly from your computer (preferred)', null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&q=80&w=1600', help_text='Or enter an external ImageKit / Unsplash image URL', max_length=800)),
                ('gradient_overlay', models.CharField(blank=True, default='from-slate-950 via-slate-950/85 to-transparent', help_text='Tailwind gradient overlay classes', max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lowest first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner on the Home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['order', 'id'],
            },
        ),
    ]
