# Generated by Django 5.2.10 on 2026-09-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_promotionalbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='booking',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Or enter an external ImageKit / banner image URL', max_length=800),
        ),
    ]
