# Generated by Django 5.2.10 on 2026-09-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_phone_number_booking_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Or enter an external ImageKit image URL', max_length=800),
        ),
    ]
