# Generated by Django 5.2.10 on 2026-09-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_booking_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Client contact number for this booking', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='requirements',
            field=models.TextField(blank=True, help_text='Specific requirements or shoot brief from the client'),
        ),
    ]
