# Generated by Django 5.2.10 on 2026-09-20 18:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_phone_number_booking_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Package name, e.g. 'Instagram Reel Package'", max_length=150)),
                ('icon', models.CharField(default='🎥', help_text='Emoji icon for this package', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration', models.CharField(blank=True, default='2 hours', help_text="e.g. '2 hours shoot' or '60 minutes'", max_length=100)),
                ('deliverables', models.JSONField(blank=True, default=list, help_text="List of deliverable strings e.g. ['5 edited photos', '1 reel']")),
                ('turnaround', models.CharField(blank=True, default='Delivery: 3 days', help_text="e.g. 'Delivery: 3 days'", max_length=100)),
                ('cover_image', models.URLField(blank=True, default='', help_text='ImageKit URL for the package cover image', max_length=800)),
                ('popular', models.BooleanField(default=False, help_text='Mark as a featured / most popular package')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_set', to='core.shooterprofile')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
