# Generated by Django 5.2.10 on 2026-09-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooterprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', help_text='Instagram handle without @ or full URL', max_length=100),
        ),
    ]
